### ISSUE TITLE
请问自启动的frida server是哪个版本的

### ISSUE THREAD

**Issue by tanchichong** [cxf-boluo/magisk_All#3]

**Comment by cxf-boluo** [comment]
![image](https://user-images.githubusercontent.com/86091961/178861387-234c2b97-8b1b-4513-b272-3f8ec91dcb27.png)
frida-server 被命名为fs 并配置到了环境变量
![image](https://user-images.githubusercontent.com/86091961/178861495-2195b293-b2a0-428c-a3a8-f8e6e9b8acfa.png)
